name: Ejecutar entrega fallida ARG/MX

on:
  workflow_dispatch:
  schedule:
    - cron: "11 11 * * *"  # 08:00 ART (UTC-3)

jobs:
  run:
    runs-on: ubuntu-latest
    environment: ENV_FALLIDA

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cargar variables del blob ENV_FALLIDA
        run: |
          echo "Cargando variables desde ENV_FALLIDA..."
          echo "${{ vars.ENV_FALLIDA }}" | tr -d '\r' | awk 'NF && $0 !~ /^#/ {print}' >> "$GITHUB_ENV"
          echo "Variables cargadas."

      - name: Ejecutar script
        env:
          GSERVICE_CREDENTIALS_JSON_CONTENT: ${{ secrets.GSERVICE_CREDENTIALS_JSON_CONTENT }}
        run: python Entrega-fallida/Entrega-fallida-CE.py
